// Auto-generated by scripts/sync-schema.js
// Do not edit directly. sync with vyasac/src/schema.sql

export const SCHEMA_SQL = `
-- Vyasa SQLite VFS & Graph Schema

-- 1. Virtual File System (VFS)
-- Stores the source code.
CREATE TABLE IF NOT EXISTS files (
    path TEXT PRIMARY KEY,       -- Virtual path (e.g., "content/1.vy")
    content TEXT NOT NULL,       -- Raw content (UTF-8)
    hash TEXT,                   -- Content hash (SHA-256) for cache invalidation
    modified_at DATETIME,        -- Last modification time (ISO8601)
    mime_type TEXT DEFAULT 'text/vyasa'
);

-- 2. Streams (Output Organization)
-- Defines compilation roots (e.g., Primary, Footnotes).
CREATE TABLE IF NOT EXISTS streams (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,   -- "primary", "footnotes", "metadata"
    type TEXT NOT NULL           -- "tree"
);

-- 3. Nodes (The Compiled Graph)
-- Stores the AST/DOM. Replaces JSON output.
CREATE TABLE IF NOT EXISTS nodes (
    id INTEGER PRIMARY KEY,      -- Auto-increment ID
    stream_id INTEGER,           -- Belongs to stream
    parent_id INTEGER,           -- Hierarchy
    
    -- Structure
    type TEXT NOT NULL,          -- "command", "text", "comment", "template", "break"
    name TEXT,                   -- Command name (e.g. "verse") or Tag name
    
    -- Data
    body TEXT,                   -- Text content or Template body
    attributes JSON,             -- Key-value pairs (stored as JSON object)
    
    -- Metadata
    urn TEXT,                    -- Universal Resource Name (if applicable)
    ordinal INTEGER,             -- Ordering within parent
    location JSON,               -- Source span {file, line, col, length}
    
    FOREIGN KEY(stream_id) REFERENCES streams(id),
    FOREIGN KEY(parent_id) REFERENCES nodes(id) ON DELETE CASCADE
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_nodes_parent ON nodes(parent_id);
CREATE INDEX IF NOT EXISTS idx_nodes_urn ON nodes(urn);
CREATE INDEX IF NOT EXISTS idx_nodes_type ON nodes(type);

-- 4. Registry (Global Quantities)
-- Stores entities and cross-reference data.
CREATE TABLE IF NOT EXISTS registry (
    name TEXT PRIMARY KEY,
    attributes JSON              -- Entity attributes
);

-- 5. Manifest (Workspace Config)
-- Stores build metadata.
CREATE TABLE IF NOT EXISTS manifest (
    key TEXT PRIMARY KEY,
    value TEXT
);

`;
