import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Path to CLI schema
const CLI_SCHEMA_PATH = path.resolve(__dirname, '../../../vyasa/vyasac/src/schema.sql');
// Path to Output TS
const OUTPUT_PATH = path.resolve(__dirname, '../src/lib/schema.ts');

try {
    console.log(`Reading schema from ${CLI_SCHEMA_PATH}...`);
    const sql = fs.readFileSync(CLI_SCHEMA_PATH, 'utf8');

    const tsContent = `// Auto-generated by scripts/sync-schema.js
// Do not edit directly. sync with vyasac/src/schema.sql

export const SCHEMA_SQL = \`
${sql}
\`;
`;

    fs.writeFileSync(OUTPUT_PATH, tsContent);
    console.log(`Schema synced to ${OUTPUT_PATH}`);

} catch (e) {
    console.error('Failed to sync schema:', e);
    process.exit(1);
}
